import type { Metadata } from "next";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";
import Header from "@/components/Header";
import Sidebar from "@/components/ui/sidebar/Sidebar";
import ReactQueryProvider from "./ReactQueryProvider";

const queryClient = new QueryClient();

export const metadata: Metadata = {
  title: "Kanban Board",
  description: "Generated by Harshil Gambhir.",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Header />
            <div className="flex flex-1 overflow-hidden">
              <Sidebar />
              {children}
            </div>
          </ThemeProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
