import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";
import type { Metadata } from "next";
import Header from "@/components/Header";
import Sidebar from "@/components/ui/sidebar/Sidebar";

export const metadata: Metadata = {
  title: "Kanban Board",
  description: "Generated by Harshil Gambhir.",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          <Sidebar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
